// App-wide event names (ported from nine-ca common/constants + common/events)
export const events = {
  MENU_OPEN: "MENU_OPEN",
  MENU_CLOSE: "MENU_CLOSE",
  MENU_OUT_COMPLETE: "MENU_OUT_COMPLETE",

  ROUTE_CHANGE_START: "ROUTE_CHANGE_START",
  ROUTE_CHANGE_COMPLETE: "ROUTE_CHANGE_COMPLETE",

  LOADING_START: "LOADING_START",
  LOADING_PROGRESS: "LOADING_PROGRESS",
  LOADING_COMPLETE: "LOADING_COMPLETE",
  LOADING_DONE: "LOADING_DONE",
  LOADING_OUT_COMPLETE: "LOADING_OUT_COMPLETE",

  SWITCH_THEME: "SWITCH_THEME",

  CURSOR_SHOW: "CURSOR_SHOW",
  CURSOR_HIDE: "CURSOR_HIDE",

  GL_BACKGROUND_IN: "GL_BACKGROUND_IN",
  GL_BACKGROUND_IN_COMPLETE: "GL_BACKGROUND_IN_COMPLETE",
  GL_BACKGROUND_OUT: "GL_BACKGROUND_OUT",
  GL_BACKGROUND_OUT_COMPLETE: "GL_BACKGROUND_OUT_COMPLETE",

  HOME_HOW_WE_DO_IT_IN: "home-how-we-do-it:in",
  HOME_HOW_WE_DO_IT_OUT: "home-how-we-do-it:out",

  PROJECTS_GRID_RESIZE: "PROJECTS_GRID_RESIZE",
  PROJECTS_ON_ENTERING: "PROJECTS:ON_ENTERING",
  HOME_ON_ENTERING: "HOME:ON_ENTERING",
};
